package br.com.model.entities;
// Generated 08-abr-2014 18:20:29 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade"
    ,catalog="semeru_jsf_maven_db"
)
public class Cidade  implements java.io.Serializable {


     private Integer idCidade;
     private String nome;
     private Set<Endereco> enderecos = new HashSet<Endereco>(0);

    public Cidade() {
    }

	
    public Cidade(String nome) {
        this.nome = nome;
    }
    public Cidade(String nome, Set<Endereco> enderecos) {
       this.nome = nome;
       this.enderecos = enderecos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdCidade", unique=true, nullable=false)
    public Integer getIdCidade() {
        return this.idCidade;
    }
    
    public void setIdCidade(Integer idCidade) {
        this.idCidade = idCidade;
    }

    
    @Column(name="Nome", nullable=false, length=80)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }




}


