package br.com.model.entities;
// Generated 08-abr-2014 18:20:29 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name="endereco"
    ,catalog="semeru_jsf_maven_db"
)
public class Endereco  implements java.io.Serializable {


     private Integer idEndereco;
     private Tipologradouro tipologradouro;
     private Estado estado;
     private Pessoa pessoa;
     private Tipoendereco tipoendereco;
     private Cidade cidade;
     private String bairro;
     private String cep;
     private Integer complemento;
     private String nomeLogradouro;
     private Integer numero;

    public Endereco() {
    }

	
    public Endereco(Tipologradouro tipologradouro, Estado estado, Tipoendereco tipoendereco, Cidade cidade) {
        this.tipologradouro = tipologradouro;
        this.estado = estado;
        this.tipoendereco = tipoendereco;
        this.cidade = cidade;
    }
    public Endereco(Tipologradouro tipologradouro, Estado estado, Pessoa pessoa, Tipoendereco tipoendereco, Cidade cidade, String bairro, String cep, Integer complemento, String nomeLogradouro, Integer numero) {
       this.tipologradouro = tipologradouro;
       this.estado = estado;
       this.pessoa = pessoa;
       this.tipoendereco = tipoendereco;
       this.cidade = cidade;
       this.bairro = bairro;
       this.cep = cep;
       this.complemento = complemento;
       this.nomeLogradouro = nomeLogradouro;
       this.numero = numero;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdEndereco", unique=true, nullable=false)
    public Integer getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(Integer idEndereco) {
        this.idEndereco = idEndereco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdTipoLogradouro", nullable=false)
    public Tipologradouro getTipologradouro() {
        return this.tipologradouro;
    }
    
    public void setTipologradouro(Tipologradouro tipologradouro) {
        this.tipologradouro = tipologradouro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdEstado", nullable=false)
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdPessoa")
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdTipoEndereco", nullable=false)
    public Tipoendereco getTipoendereco() {
        return this.tipoendereco;
    }
    
    public void setTipoendereco(Tipoendereco tipoendereco) {
        this.tipoendereco = tipoendereco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCidade", nullable=false)
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="Bairro", length=80)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="CEP", length=9)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="Complemento")
    public Integer getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(Integer complemento) {
        this.complemento = complemento;
    }

    
    @Column(name="NomeLogradouro", length=80)
    public String getNomeLogradouro() {
        return this.nomeLogradouro;
    }
    
    public void setNomeLogradouro(String nomeLogradouro) {
        this.nomeLogradouro = nomeLogradouro;
    }

    
    @Column(name="Numero")
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }




}


