package br.com.model.entities;
// Generated 08-abr-2014 18:20:29 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="estado"
    ,catalog="semeru_jsf_maven_db"
)
public class Estado  implements java.io.Serializable {


     private Integer idEstado;
     private String nomeEstado;
     private Set<Endereco> enderecos = new HashSet<Endereco>(0);

    public Estado() {
    }

	
    public Estado(String nomeEstado) {
        this.nomeEstado = nomeEstado;
    }
    public Estado(String nomeEstado, Set<Endereco> enderecos) {
       this.nomeEstado = nomeEstado;
       this.enderecos = enderecos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdEstado", unique=true, nullable=false)
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="NomeEstado", nullable=false, length=40)
    public String getNomeEstado() {
        return this.nomeEstado;
    }
    
    public void setNomeEstado(String nomeEstado) {
        this.nomeEstado = nomeEstado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }




}


