package br.com.model.entities;
// Generated 08-abr-2014 18:20:29 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name="pessoa"
    ,catalog="semeru_jsf_maven_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="Login") 
)
public class Pessoa  implements java.io.Serializable {


     private Integer idPessoa;
     private Sexo sexo;
     private String cpf;
     private Date dataDeCadastro;
     private Date dataDeNascimento;
     private String email;
     private String login;
     private String name;
     private String permissao;
     private String senha;
     private String telefone;
     private Set<Endereco> enderecos = new HashSet<Endereco>(0);

    public Pessoa() {
    }

	
    public Pessoa(Sexo sexo, String cpf, Date dataDeCadastro, Date dataDeNascimento, String email, String name, String telefone) {
        this.sexo = sexo;
        this.cpf = cpf;
        this.dataDeCadastro = dataDeCadastro;
        this.dataDeNascimento = dataDeNascimento;
        this.email = email;
        this.name = name;
        this.telefone = telefone;
    }
    public Pessoa(Sexo sexo, String cpf, Date dataDeCadastro, Date dataDeNascimento, String email, String login, String name, String permissao, String senha, String telefone, Set<Endereco> enderecos) {
       this.sexo = sexo;
       this.cpf = cpf;
       this.dataDeCadastro = dataDeCadastro;
       this.dataDeNascimento = dataDeNascimento;
       this.email = email;
       this.login = login;
       this.name = name;
       this.permissao = permissao;
       this.senha = senha;
       this.telefone = telefone;
       this.enderecos = enderecos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdPessoa", unique=true, nullable=false)
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdSexo", nullable=false)
    public Sexo getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="CPF", nullable=false, length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DataDeCadastro", nullable=false, length=10)
    public Date getDataDeCadastro() {
        return this.dataDeCadastro;
    }
    
    public void setDataDeCadastro(Date dataDeCadastro) {
        this.dataDeCadastro = dataDeCadastro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DataDeNascimento", nullable=false, length=10)
    public Date getDataDeNascimento() {
        return this.dataDeNascimento;
    }
    
    public void setDataDeNascimento(Date dataDeNascimento) {
        this.dataDeNascimento = dataDeNascimento;
    }

    
    @Column(name="Email", nullable=false, length=80)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Login", unique=true, length=25)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="Name", nullable=false, length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Permissao", length=36)
    public String getPermissao() {
        return this.permissao;
    }
    
    public void setPermissao(String permissao) {
        this.permissao = permissao;
    }

    
    @Column(name="Senha", length=40)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="Telefone", nullable=false, length=15)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }




}


