package br.com.model.entities;
// Generated 08-abr-2014 18:20:29 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sexo generated by hbm2java
 */
@Entity
@Table(name="sexo"
    ,catalog="semeru_jsf_maven_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="Descricao") 
)
public class Sexo  implements java.io.Serializable {


     private Integer idSexo;
     private String descricao;
     private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

    public Sexo() {
    }

	
    public Sexo(String descricao) {
        this.descricao = descricao;
    }
    public Sexo(String descricao, Set<Pessoa> pessoas) {
       this.descricao = descricao;
       this.pessoas = pessoas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdSexo", unique=true, nullable=false)
    public Integer getIdSexo() {
        return this.idSexo;
    }
    
    public void setIdSexo(Integer idSexo) {
        this.idSexo = idSexo;
    }

    
    @Column(name="Descricao", unique=true, nullable=false, length=9)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sexo")
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }




}


