package br.com.model.entities;
// Generated 08-abr-2014 18:20:29 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoendereco generated by hbm2java
 */
@Entity
@Table(name="tipoendereco"
    ,catalog="semeru_jsf_maven_db"
)
public class Tipoendereco  implements java.io.Serializable {


     private Integer idTipoEndereco;
     private String descricaoTipoEndereco;
     private Set<Endereco> enderecos = new HashSet<Endereco>(0);

    public Tipoendereco() {
    }

	
    public Tipoendereco(String descricaoTipoEndereco) {
        this.descricaoTipoEndereco = descricaoTipoEndereco;
    }
    public Tipoendereco(String descricaoTipoEndereco, Set<Endereco> enderecos) {
       this.descricaoTipoEndereco = descricaoTipoEndereco;
       this.enderecos = enderecos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdTipoEndereco", unique=true, nullable=false)
    public Integer getIdTipoEndereco() {
        return this.idTipoEndereco;
    }
    
    public void setIdTipoEndereco(Integer idTipoEndereco) {
        this.idTipoEndereco = idTipoEndereco;
    }

    
    @Column(name="DescricaoTipoEndereco", nullable=false, length=35)
    public String getDescricaoTipoEndereco() {
        return this.descricaoTipoEndereco;
    }
    
    public void setDescricaoTipoEndereco(String descricaoTipoEndereco) {
        this.descricaoTipoEndereco = descricaoTipoEndereco;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoendereco")
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }




}


