package br.com.model.entities;
// Generated 08-abr-2014 18:20:29 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipologradouro generated by hbm2java
 */
@Entity
@Table(name="tipologradouro"
    ,catalog="semeru_jsf_maven_db"
)
public class Tipologradouro  implements java.io.Serializable {


     private Integer idTipoLogradouro;
     private String descricaoTipoLogradouro;
     private Set<Endereco> enderecos = new HashSet<Endereco>(0);

    public Tipologradouro() {
    }

	
    public Tipologradouro(String descricaoTipoLogradouro) {
        this.descricaoTipoLogradouro = descricaoTipoLogradouro;
    }
    public Tipologradouro(String descricaoTipoLogradouro, Set<Endereco> enderecos) {
       this.descricaoTipoLogradouro = descricaoTipoLogradouro;
       this.enderecos = enderecos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdTipoLogradouro", unique=true, nullable=false)
    public Integer getIdTipoLogradouro() {
        return this.idTipoLogradouro;
    }
    
    public void setIdTipoLogradouro(Integer idTipoLogradouro) {
        this.idTipoLogradouro = idTipoLogradouro;
    }

    
    @Column(name="DescricaoTipoLogradouro", nullable=false, length=40)
    public String getDescricaoTipoLogradouro() {
        return this.descricaoTipoLogradouro;
    }
    
    public void setDescricaoTipoLogradouro(String descricaoTipoLogradouro) {
        this.descricaoTipoLogradouro = descricaoTipoLogradouro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipologradouro")
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }




}


